# Generated by Django 4.1.4 on 2023-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_profile', models.CharField(max_length=100)),
                ('work_ex', models.IntegerField()),
                ('experience', models.CharField(max_length=700)),
            ],
        ),
    ]
