# Generated by Django 4.1.4 on 2023-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='experience',
            field=models.CharField(max_length=2000),
        ),
    ]
