# Generated by Django 4.1.4 on 2023-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='owner', max_length=50),
            preserve_default=False,
        ),
    ]
