# Generated by Django 4.1.4 on 2023-01-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='savedby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
