# Generated by Django 4.1.4 on 2023-01-21 18:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_savedby_blog_favourites_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='company_name', unique=True),
        ),
    ]
