# Generated by Django 4.1.4 on 2023-01-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
