# Generated by Django 4.1.4 on 2023-01-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile_age_profile_college_profile_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
