# Generated by Django 4.1.4 on 2023-01-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='NEW', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='NEW', max_length=100),
            preserve_default=False,
        ),
    ]
