# Generated by Django 4.1.4 on 2023-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_profile_email_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
