# Generated by Django 4.1.4 on 2023-01-29 04:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
