# Generated by Django 4.1.4 on 2023-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_pass_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
