# Generated by Django 4.1.4 on 2023-02-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_profile_forget_pass_token_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
