# Generated by Django 4.1.4 on 2023-02-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currwork',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
